from pptx import Presentation
from pptx.util import Inches
import textwrap

def generate_content(topic):
    """
    Generate slide content dynamically based on the topic.
    You can modify this function to fetch data from an API or AI model.
    """
    topic_info = {
        "Computer": [
            {"title": "Introduction to Computers", "text": "A computer is an electronic device that processes data."},
            {"title": "Components of a Computer", "text": "1. CPU 2. Memory 3. Storage 4. Input/Output Devices"},
            {"title": "Uses of Computers", "text": "Used in education, business, entertainment, and research."},
            {"title": "Conclusion", "text": "Computers have revolutionized the modern world."}
        ],
        "Artificial Intelligence": [
            {"title": "Introduction to AI", "text": "AI enables machines to simulate human intelligence."},
            {"title": "Types of AI", "text": "1. Narrow AI 2. General AI 3. Super AI"},
            {"title": "Applications of AI", "text": "Used in healthcare, finance, robotics, and more."},
            {"title": "Conclusion", "text": "AI is transforming various industries."}
        ]
    }

    return topic_info.get(topic, [{"title": "No Data", "text": "Content not available for this topic."}])

def create_presentation(topic, output_file="Generated_Presentation.pptx"):
    prs = Presentation()
    
    # Title Slide
    slide_layout = prs.slide_layouts[0]  # Title slide layout
    slide = prs.slides.add_slide(slide_layout)
    title_placeholder = slide.shapes.title
    subtitle_placeholder = slide.placeholders[1]
    title_placeholder.text = topic
    subtitle_placeholder.text = "Generated by Smart Presentation Generator"
    
    # Generate content based on topic
    content_list = generate_content(topic)
    
    # Content Slides
    for content in content_list:
        slide_layout = prs.slide_layouts[1]  # Title and Content layout
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        body = slide.placeholders[1]
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        body.text = wrapped_text
    
    # Save the presentation
    prs.save(output_file)
    print(f"Presentation saved as {output_file}")

# Example Usage - Auto-generate a PPT for a topic
if __name__ == "__main__":
    topic = input("Enter the topic for the presentation: ")  # User inputs topic
    create_presentation(topic)
