import os
from pptx import Presentation
import textwrap

def generate_content(topic):
    """
    Generates slide content dynamically based on the topic.
    Modify this function to fetch data from an AI model, API, or database.
    """
    default_content = [
        {"title": f"Introduction to {topic}", "text": f"{topic} is an important subject that plays a crucial role in various fields."},
        {"title": f"Key Aspects of {topic}", "text": f"1. Definition 2. Importance 3. Applications 4. Future Scope"},
        {"title": f"Applications of {topic}", "text": f"{topic} is used in education, business, research, and entertainment."},
        {"title": "Conclusion", "text": f"{topic} continues to evolve and impact our daily lives."}
    ]
    return default_content

def create_presentation(topic, output_file=None):
    """
    Creates a PowerPoint presentation (.pptx) based on user input.
    """
    if output_file is None:
        output_file = f"{topic.replace(' ', '_')}_Presentation.pptx"

    # Ensure the file isn't open before overwriting
    if os.path.exists(output_file):
        try:
            os.remove(output_file)
        except PermissionError:
            print(f"❌ Cannot overwrite {output_file}. Close the file and try again.")
            return

    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]  # Title slide layout
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = topic
    slide.placeholders[1].text = "Generated by Smart Presentation Generator"
    
    # Generate slides based on topic
    content_list = generate_content(topic)
    
    for content in content_list:
        slide_layout = prs.slide_layouts[1]  # Title and Content layout
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        body = slide.placeholders[1]
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        body.text = wrapped_text
    
    # Save the presentation
    prs.save(output_file)
    print(f"✅ Presentation saved as {output_file}")

# Main function to take input and generate PPT
if __name__ == "__main__":
    topic = input("Enter the topic for the presentation: ")  # Get topic from user
    create_presentation(topic)
