from flask import Flask, request, send_file, render_template
from pptx import Presentation
import textwrap
from serpapi import GoogleSearch
import os

app = Flask(__name__)

SERPAPI_API_KEY = "YOUR_NEW_API_KEY"  # Replace with your real SerpAPI key

def fetch_google_results(topic):
    """Fetches top search results from Google using SerpApi."""
    params = {
        "q": topic,
        "api_key": SERPAPI_API_KEY,
        "num": 3
    }
    
    try:
        search = GoogleSearch(params)
        results = search.get_dict()
        
        content_list = []
        if "organic_results" in results:
            for i, result in enumerate(results["organic_results"][:3]):
                title = result.get("title", f"Topic {i+1}")
                snippet = result.get("snippet", "No description available")
                content_list.append({"title": title, "text": snippet})
        
        return content_list if content_list else [{"title": "No Data", "text": "No search results found."}]
    
    except Exception as e:
        print(f"⚠️ Error fetching search results: {e}")
        return [{"title": "Error", "text": "Could not fetch search results."}]

def create_presentation(topic, output_file="static/Generated_Presentation.pptx"):
    """Creates a PowerPoint presentation and saves it."""
    
    # Ensure the static directory exists
    os.makedirs("static", exist_ok=True)

    prs = Presentation()
    
    # Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = topic

    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI-based Presentation Generator"

    # Fetch content dynamically from Google
    content_list = fetch_google_results(topic)

    # Content Slides
    for content in content_list:
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        body = slide.placeholders[1] if len(slide.placeholders) > 1 else None 
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        
        if body:
            body.text = wrapped_text

    try:
        prs.save(output_file)
        print(f"✅ Presentation saved as {output_file}")
        return output_file
    except PermissionError:
        print("❌ Error: Permission denied. Close the PowerPoint file if it's open and try again.")
        return None

@app.route("/")
def index():
    return render_template("index.html")  # Load the frontend HTML page

@app.route("/generate", methods=["POST"])
def generate():
    topic = request.form["topic"]
    pptx_file = create_presentation(topic)
    
    if pptx_file:
        return {"download_link": "/download"}
    else:
        return {"error": "Failed to generate presentation"}, 500

@app.route("/download")
def download():
    pptx_path = "static/Generated_Presentation.pptx"
    if os.path.exists(pptx_path):
        return send_file(pptx_path, as_attachment=True)
    return "File not found", 404

if __name__ == "__main__":
    app.run(debug=True)
