from pptx import Presentation
from pptx.util import Inches
import textwrap

def create_presentation(title, content_list, output_file="Smart_Presentation.pptx"):
    prs = Presentation()
    
    # Title Slide
    slide_layout = prs.slide_layouts[0]  # Title slide layout
    slide = prs.slides.add_slide(slide_layout)
    title_placeholder = slide.shapes.title
    subtitle_placeholder = slide.placeholders[1]
    title_placeholder.text = title
    subtitle_placeholder.text = "Generated by Smart Presentation Generator"
    
    # Content Slides
    for content in content_list:
        slide_layout = prs.slide_layouts[1]  # Title and Content layout
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        body = slide.placeholders[1]
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        body.text = wrapped_text
    
    # Save the presentation
    prs.save(output_file)
    print(f"Presentation saved as {output_file}")

# Example Usage
if __name__ == "__main__":
    title = "Smart Presentation Generator"
    content_list = [
        {"title": "Introduction", "text": "This is an AI-based presentation generator that automates slide creation."},
        {"title": "Features", "text": "1. Generates slides from text input. 2. Auto-formats content. 3. Saves as PowerPoint file."},
        {"title": "Conclusion", "text": "Smart presentations save time and improve efficiency."}
    ]
    
    create_presentation(title, content_list)
