from pptx import Presentation
import textwrap
from serpapi import GoogleSearch

SERPAPI_API_KEY = "YOUR_SERPAPI_API_KEY"

def fetch_google_results(topic):
    """Fetches top search results from Google using SerpApi."""
    params = {
        "q": topic,
        "api_key": SERPAPI_API_KEY,
        "num": 3  
    }
    
    try:
        search = GoogleSearch(params)
        results = search.get_dict()
        
        content_list = []
        if "organic_results" in results:
            for i, result in enumerate(results["organic_results"][:3]):
                title = result.get("title", f"Topic {i+1}")
                snippet = result.get("snippet", "No description available")
                content_list.append({"title": title, "text": snippet})
        
        return content_list if content_list else [{"title": "No Data", "text": "No search results found."}]
    
    except Exception as e:
        print(f"⚠️ Error fetching search results: {e}")
        return [{"title": "Error", "text": "Could not fetch search results."}]

def create_presentation(topic, output_file="Generated_Presentation.pptx", template_file="template.pptx"):
    # ✅ Load a PowerPoint template instead of creating a blank presentation
    try:
        prs = Presentation(template_file)
    except Exception as e:
        print(f"⚠️ Could not load template: {e}")
        prs = Presentation()  # Fallback to default
    
    # ✅ Title Slide
    slide_layout = prs.slide_layouts[0]  
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = topic
    
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI-based Presentation Generator"
    
    # ✅ Fetch content dynamically from Google
    content_list = fetch_google_results(topic)
    
    # ✅ Content Slides
    for content in content_list:
        slide_layout = prs.slide_layouts[1]  
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        body = slide.placeholders[1] if len(slide.placeholders) > 1 else None  
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        
        if body:
            body.text = wrapped_text
    
    # ✅ Save the presentation
    try:
        prs.save(output_file)
        print(f"✅ Presentation saved as {output_file}")
    except PermissionError:
        print("❌ Error: Permission denied. Close the PowerPoint file if it's open and try again.")

if __name__ == "__main__":
    topic = input("Enter the topic for the presentation: ")  
    create_presentation(topic)
