from pptx import Presentation
import textwrap
from serpapi import GoogleSearch


SERPAPI_API_KEY = "a456c6b1ed841e5b44e3a56ada7853cd29ae0e93ab2cd77c4018fc1c8eb09dcd"  

def fetch_google_results(topic):
    """Fetches top search results from Google using SerpApi."""
    params = {
        "q": topic,
        "api_key": SERPAPI_API_KEY,
        "num": 3 
    }
    
    try:
        search = GoogleSearch(params)
        results = search.get_dict()
        
        content_list = []
        if "organic_results" in results:
            for i, result in enumerate(results["organic_results"][:3]):
                title = result.get("title", f"Topic {i+1}")
                snippet = result.get("snippet", "No description available")
                content_list.append({"title": title, "text": snippet})
        
        return content_list if content_list else [{"title": "No Data", "text": "No search results found."}]
    
    except Exception as e:
        print(f"⚠️ Error fetching search results: {e}")
        return [{"title": "Error", "text": "Could not fetch search results."}]

def create_presentation(topic, output_file="Generated_Presentation.pptx", template_file="theme1.pptx"):
    try:
        prs = Presentation(template_file)
    except Exception as e:
        print(f"Could not load")
        prs=Presentation()

    slide_layout = prs.slide_layouts[0] 
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = topic
    
    
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI-based Presentation Generator from Bug Slayers"
    
    
    content_list = fetch_google_results(topic)

    for content in content_list:
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        body = slide.placeholders[1] if len(slide.placeholders) > 1 else None 
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        
        if body:
            body.text = wrapped_text

    try:
        prs.save(output_file)
        print(f"✅ Presentation saved as {output_file}")
    except PermissionError:
        print("❌ Error: Permission denied. Close the PowerPoint file if it's open and try again.")

if __name__ == "__main__":
    topic = input("Enter the topic for the presentation: ")  
    create_presentation(topic)
from pptx import Presentation
import textwrap
from serpapi import GoogleSearch

SERPAPI_API_KEY = "a456c6b1ed841e5b44e3a56ada7853cd29ae0e93ab2cd77c4018fc1c8eb09dcd"  

def fetch_google_results(topic):
    """Fetches top search results from Google using SerpApi."""
    params = {
        "q": topic,
        "api_key": SERPAPI_API_KEY,
        "num": 3
    }
    
    try:
        search = GoogleSearch(params)
        results = search.get_dict()
        
        content_list = []
        if "organic_results" in results:
            for i, result in enumerate(results["organic_results"][:3]):
                title = result.get("title", f"Topic {i+1}")
                snippet = result.get("snippet", "No description available")
                content_list.append({"title": title, "text": snippet})
        
        return content_list if content_list else [{"title": "No Data", "text": "No search results found."}]
    
    except Exception as e:
        print(f"⚠️ Error fetching search results: {e}")
        return [{"title": "Error", "text": "Could not fetch search results."}]

def create_presentation(topic, output_file="Generated_Presentation.pptx"):
    prs = Presentation()
    
    slide_layout = prs.slide_layouts[0] 
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = topic
    
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI-based Presentation Generator"
    
    content_list = fetch_google_results(topic)
    
    for content in content_list:
        slide_layout = prs.slide_layouts[1] 
        slide = prs.slides.add_slide(slide_layout)
        
        title = slide.shapes.title
        body = slide.placeholders[1] if len(slide.placeholders) > 1 else None 
        
        title.text = content["title"]
        wrapped_text = "\n".join(textwrap.wrap(content["text"], width=80))
        
        if body:
            body.text = wrapped_text
    
    try:
        prs.save(output_file)
        print(f"✅ Presentation saved as {output_file}")
    except PermissionError:
        print("❌ Error: Permission denied. Close the PowerPoint file if it's open and try again.")

if __name__ == "__main__":
    topic = input("Enter the topic for the presentation: ")
    create_presentation(topic)